var sourcesIndex = JSON.parse('{\
"example_appservice_autojoin":["",[],["main.rs"]],\
"example_autojoin":["",[],["main.rs"]],\
"example_command_bot":["",[],["main.rs"]],\
"example_cross_signing_bootstrap":["",[],["main.rs"]],\
"example_custom_events":["",[],["main.rs"]],\
"example_emoji_verification":["",[],["main.rs"]],\
"example_get_profiles":["",[],["main.rs"]],\
"example_getting_started":["",[],["main.rs"]],\
"example_image_bot":["",[],["main.rs"]],\
"example_login":["",[],["main.rs"]],\
"example_persist_session":["",[],["main.rs"]],\
"example_timeline":["",[],["main.rs"]],\
"matrix_sdk":["",[["client",[],["builder.rs","futures.rs","mod.rs"]],["config",[],["mod.rs","request.rs","sync.rs"]],["encryption",[["identities",[],["devices.rs","mod.rs","users.rs"]],["verification",[],["mod.rs","qrcode.rs","requests.rs","sas.rs"]]],["futures.rs","mod.rs"]],["event_handler",[],["context.rs","maps.rs","mod.rs","static_events.rs"]],["http_client",[],["mod.rs","native.rs"]],["matrix_auth",[],["login_builder.rs","mod.rs"]],["notification_settings",[],["mod.rs","rules.rs"]],["room",[["joined",[],["futures.rs","mod.rs"]]],["common.rs","invited.rs","left.rs","member.rs","mod.rs"]],["sliding_sync",[["list",[],["builder.rs","frozen.rs","mod.rs","request_generator.rs","room_list_entry.rs","sticky.rs"]]],["builder.rs","cache.rs","client.rs","error.rs","mod.rs","room.rs","sticky_parameters.rs"]]],["account.rs","attachment.rs","authentication.rs","error.rs","lib.rs","media.rs","sync.rs","test_utils.rs"]],\
"matrix_sdk_appservice":["",[],["error.rs","event_handler.rs","lib.rs","registration.rs","user.rs","webserver.rs"]],\
"matrix_sdk_base":["",[["rooms",[],["members.rs","mod.rs","normal.rs"]],["store",[],["ambiguity_map.rs","memory_store.rs","mod.rs","traits.rs"]]],["client.rs","debug.rs","deserialized_responses.rs","error.rs","lib.rs","media.rs","sliding_sync.rs","sync.rs","utils.rs"]],\
"matrix_sdk_common":["",[],["debug.rs","deserialized_responses.rs","executor.rs","lib.rs","ring_buffer.rs","timeout.rs"]],\
"matrix_sdk_crypto":["",[["backups",[["keys",[],["backup.rs","compat.rs","mod.rs","recovery.rs"]]],["mod.rs"]],["file_encryption",[],["attachments.rs","key_export.rs","mod.rs"]],["gossiping",[],["machine.rs","mod.rs"]],["identities",[],["device.rs","manager.rs","mod.rs","user.rs"]],["olm",[["group_sessions",[],["inbound.rs","mod.rs","outbound.rs"]],["signing",[],["mod.rs","pk_signing.rs"]]],["account.rs","mod.rs","session.rs","utility.rs"]],["session_manager",[],["group_sessions.rs","mod.rs","sessions.rs"]],["store",[],["caches.rs","error.rs","integration_tests.rs","locks.rs","memorystore.rs","mod.rs","traits.rs"]],["types",[["cross_signing",[],["common.rs","master.rs","mod.rs","self_signing.rs","user_signing.rs"]],["events",[["room",[],["encrypted.rs","mod.rs"]]],["dummy.rs","forwarded_room_key.rs","mod.rs","olm_v1.rs","room_key.rs","room_key_request.rs","room_key_withheld.rs","secret_send.rs","to_device.rs"]]],["backup.rs","device_keys.rs","mod.rs","one_time_keys.rs"]],["verification",[["sas",[],["helpers.rs","inner_sas.rs","mod.rs","sas_state.rs"]]],["cache.rs","event_enums.rs","machine.rs","mod.rs","qrcode.rs","requests.rs"]]],["error.rs","lib.rs","machine.rs","requests.rs","utilities.rs"]],\
"matrix_sdk_crypto_ffi":["",[],["backup_recovery_key.rs","device.rs","error.rs","lib.rs","logger.rs","machine.rs","responses.rs","users.rs","verification.rs"]],\
"matrix_sdk_crypto_js":["",[],["attachment.rs","device.rs","encryption.rs","events.rs","future.rs","identifiers.rs","identities.rs","js.rs","lib.rs","machine.rs","macros.rs","olm.rs","requests.rs","responses.rs","store.rs","sync_events.rs","tracing.rs","types.rs","verification.rs","vodozemac.rs"]],\
"matrix_sdk_crypto_nodejs":["",[],["attachment.rs","encryption.rs","errors.rs","events.rs","identifiers.rs","lib.rs","machine.rs","olm.rs","requests.rs","responses.rs","sync_events.rs","types.rs","vodozemac.rs"]],\
"matrix_sdk_ffi":["",[],["authentication_service.rs","client.rs","client_builder.rs","encryption_sync.rs","error.rs","event.rs","helpers.rs","lib.rs","notification.rs","platform.rs","room.rs","room_list.rs","room_member.rs","session_verification.rs","sliding_sync.rs","task_handle.rs","timeline.rs","tracing.rs"]],\
"matrix_sdk_indexeddb":["",[["state_store",[],["migrations.rs","mod.rs"]]],["crypto_store.rs","lib.rs","safe_encode.rs"]],\
"matrix_sdk_integration_testing":["",[],["lib.rs"]],\
"matrix_sdk_qrcode":["",[],["error.rs","lib.rs","types.rs","utils.rs"]],\
"matrix_sdk_sqlite":["",[],["crypto_store.rs","error.rs","lib.rs","state_store.rs","utils.rs"]],\
"matrix_sdk_store_encryption":["",[],["lib.rs"]],\
"matrix_sdk_test":["",[["event_builder",[],["bulk.rs","invited_room.rs","joined_room.rs","left_room.rs","mod.rs","test_event.rs"]],["test_json",[],["api_responses.rs","members.rs","messages.rs","mod.rs","search_users.rs","sync.rs","sync_events.rs"]]],["lib.rs"]],\
"matrix_sdk_test_macros":["",[],["lib.rs"]],\
"matrix_sdk_ui":["",[["encryption_sync",[],["mod.rs"]],["room_list_service",[],["mod.rs","room.rs","room_list.rs","state.rs"]],["timeline",[["event_item",[],["content.rs","local.rs","mod.rs","remote.rs"]]],["builder.rs","event_handler.rs","futures.rs","inner.rs","mod.rs","pagination.rs","queue.rs","reactions.rs","read_receipts.rs","sliding_sync_ext.rs","to_device.rs","traits.rs","virtual_item.rs"]]],["events.rs","lib.rs"]],\
"sliding_sync_integration_test":["",[],["lib.rs"]],\
"uniffi_bindgen":["",[],["main.rs"]],\
"wasm_command_bot":["",[],["lib.rs"]],\
"xtask":["",[],["ci.rs","fixup.rs","kotlin.rs","main.rs","swift.rs","workspace.rs"]]\
}');
createSourceSidebar();
